[package]
name = "deravel-kernel"
version = "0.0.0"
edition = "2024"

[dependencies]
# TODO: Rust artifact dependencies ignore forced-target.
#deravel-apps = { path = "../apps", artifact = "bin" }
#deravel-filesystem-fat = { path = "../filesystems/fat", artifact = "bin" }
deravel-types = { path = "../types" }
elf = { version = "0.8", default-features = false }
fdt = { version = "0.1", features = ["pretty-printing"] }
itertools = { version = "0.15", default-features = false }
log = "0.4"
postcard = { version = "1.1", features = ["alloc"] }
riscv = "0.16"
smoltcp = { version = "0.12", features = ["log", "medium-ethernet", "proto-ipv4", "socket-dns", "socket-udp"], default-features = false }

[build-dependencies]
deravel-codegen = { path = "../codegen" }
