[unstable]
bindeps = true
build-std = ["alloc", "compiler_builtins", "core"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[target.riscv64gc-unknown-none-elf]
runner = "kernel/qemu-wrapper.sh"
rustflags = [
    "-C", "relocation-model=pie",
    "-C", "link-args=-pie",
    "-C", "link-args=--no-dynamic-linker",
    "-C", "force-frame-pointers=yes",
]

[target.riscv64gc-unknown-deravel]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "force-frame-pointers=yes",
]
